<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\Logos\Logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\Logos\Logo.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.1.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0 " />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Commands\" />
    <Folder Include="Helpers\" />
    <Folder Include="ViewModels\Pages\" />
    <Folder Include="Views\Pages\" />
  </ItemGroup>

</Project>
